// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIZTgnie7Ei738DC8lrE1LP5VvC2GBngQ',
    appId: '1:153143079048:web:87337f5b913882f2786f3d',
    messagingSenderId: '153143079048',
    projectId: 'prueba-database-841f3',
    authDomain: 'prueba-database-841f3.firebaseapp.com',
    storageBucket: 'prueba-database-841f3.firebasestorage.app',
    measurementId: 'G-ZRKQ21XTNH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtaFj8WAc35DmvCDEcWiftXeFzjPvSr50',
    appId: '1:153143079048:android:f7412772cb096f79786f3d',
    messagingSenderId: '153143079048',
    projectId: 'prueba-database-841f3',
    storageBucket: 'prueba-database-841f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC6NVHNf05936zFJcQVpzYDtvKMexk6bI',
    appId: '1:153143079048:ios:b9e4d0a813862695786f3d',
    messagingSenderId: '153143079048',
    projectId: 'prueba-database-841f3',
    storageBucket: 'prueba-database-841f3.firebasestorage.app',
    iosBundleId: 'com.example.talllerJwtFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC6NVHNf05936zFJcQVpzYDtvKMexk6bI',
    appId: '1:153143079048:ios:b9e4d0a813862695786f3d',
    messagingSenderId: '153143079048',
    projectId: 'prueba-database-841f3',
    storageBucket: 'prueba-database-841f3.firebasestorage.app',
    iosBundleId: 'com.example.talllerJwtFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIZTgnie7Ei738DC8lrE1LP5VvC2GBngQ',
    appId: '1:153143079048:web:288349d0b53e0c6c786f3d',
    messagingSenderId: '153143079048',
    projectId: 'prueba-database-841f3',
    authDomain: 'prueba-database-841f3.firebaseapp.com',
    storageBucket: 'prueba-database-841f3.firebasestorage.app',
    measurementId: 'G-SQWL687PW3',
  );
}
